const pth=location.pathname, b=document.getElementById('body');
if(pth=='/passport')b.innerHTML=`<div class="card"><div class="form"><div class="field"><label>Full name</label><input id="name" placeholder="e.g. Ankita Vashist"></div><div class="field"><label>Email</label><input id="email" placeholder="name@email.com"></div><div class="field"><label>Education</label><input id="education" placeholder="e.g. B.Tech CSE"></div><div class="field"><label>Experience</label><input id="experience" type="number" min="0" step=".5" placeholder="Years"></div><div class="field"><label>Career break</label><input id="careerBreak" type="number" min="0" step=".5" placeholder="Years"></div><div class="field"><label>Location</label><input id="locationx" placeholder="e.g. Chandigarh"></div><div class="field"><label>Work preference</label><select id="work"><option>Any</option><option>Remote</option><option>Hybrid</option><option>Onsite</option></select></div><div class="field"><label>Target role</label><input id="role" placeholder="e.g. Data Analyst"></div></div><p class="muted" style="font-size:11px">Career breaks stay as context — not just a blank gap.</p><div class="right"><button class="btn" onclick="save()">Save & continue →</button></div></div>`;
if(pth=='/resume')b.innerHTML=`<div class="card"><div class="upload"><div style="font-size:36px">◈</div><h3>Upload your resume</h3><p class="muted" style="font-size:11px">PDF, DOCX or TXT</p><input id="resumeFile" type="file" accept=".pdf,.docx,.txt" style="margin-top:12px"><div id="fileName" class="muted" style="font-size:10px;margin-top:8px">No file selected</div></div><div class="right" style="margin-top:16px"><button class="btn" onclick="analyze()">Analyze resume ✦</button></div></div><div id="resumeOut" style="margin-top:15px"></div>`;
if(pth=='/dashboard')b.innerHTML='<div id="dash"></div>';
if(pth=='/jobs')b.innerHTML='<div class="card" style="margin-bottom:15px"><div class="grid4"><div class="field"><label>Search</label><input id="jobSearch" oninput="renderJobs()" placeholder="Python, Analyst, AI..."></div><div class="field"><label>Location</label><select id="jobLocation" onchange="renderJobs()"><option value="">All locations</option></select></div><div class="field"><label>Work mode</label><select id="jobMode" onchange="renderJobs()"><option value="">Any mode</option><option>Remote</option><option>Hybrid</option><option>Onsite</option></select></div><div class="field"><label>Minimum match</label><select id="minMatch" onchange="renderJobs()"><option value="0">All</option><option value="60">60%+</option><option value="70">70%+</option><option value="80">80%+</option></select></div></div></div><div id="jobsList" class="jobgrid"></div>';
if(pth=='/gap')b.innerHTML='<div id="gapOut"></div>';
if(pth=='/assessment')b.innerHTML='<div id="quiz"></div><div class="right"><button class="btn" onclick="submitQuiz()">Submit assessment →</button></div><div id="assessmentOut" style="margin-top:15px"></div>';
if(pth=='/reskill')b.innerHTML='<div id="reskillOut"></div>';
if(pth=='/whatif')b.innerHTML='<div id="whatifOut"></div>';
